# Generated by Django 4.1.3 on 2023-03-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Uapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
